# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        description: 'Target environment production'
        required: true
        default: 'production'
        type: 'string'
          

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup nodejs
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the app
      - name: Build app
        run: npm run build

      # Clean old files beforehand
      - name: Clean and deploy to production server
        if: ${{ github.event.inputs.environment == 'production' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            echo "Cleaning target directory..."
            rm -rf /var/www/dopaminegateway.online/*
            echo "Uploading new build..."

      # Deploy to prod server
      - name: Deploy to production server
        if: ${{ github.event.inputs.environment == 'production' }}
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "dist/."
          target: "/var/www/dopaminegateway.online"
